platform :ios, '12.0'
use_frameworks!

target 'ChatLayout_Example' do
  pod 'ChatLayout', :path => '../'
  pod 'InputBarAccessoryView'
  pod 'DifferenceKit'
  pod 'FPSCounter', '~> 4.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxSwiftExt'
  pod 'RxViewController'

  target 'ChatLayout_Tests' do
    inherit! :search_paths

    
  end
end
